[package]
name = "raytracer"
version = "0.1.0"
authors = ["Pablo Tato Ramos <pabtatoramos@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
pixels = "0.2.0"
winit = "0.24.0"
winit_input_helper = "0.9.0"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
